### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by melwinek** [slackr31337/PorcupinePipeline#17]
For other language support, it would be useful to support the --keyword-paths and --model-path arguments as Environment Variables. And linking Volumes with these files.

**Comment by slackr31337** [comment]
Hello. I have updated the environment variables to include KEYWORD_PATHS, MODEL_PATH, etc.

You can also mount a path in the docker container and use that has the full path

https://github.com/slackr31337/PorcupinePipeline/commit/a9e0362dc5cd1af8812caf1196cdc73948d41149

**Comment by slackr31337** [comment]
Hi [melwinek](https://github.com/melwinek),

Since the environment variables have been added, I'm going to close this issue for now. Thanks.

Robert

**Comment by slackr31337** [comment]
Hi [melwinek](https://github.com/melwinek),

Since the environment variables have been added, I'm going to close this issue for now. Thanks.

Robert
