### ISSUE TITLE
Each container consumes Picovoice MAU

### ISSUE THREAD

**Issue by pl4nty** [slackr31337/PorcupinePipeline#22]
While troubleshooting audio in my container, I ran into a Picovoice error:

> AccessKey *** has reached it's [sic] temporary device limit

It looks like each execution counts as a unique user to Picovoice, so I have to wait a month until trying again. Would this be worth mentioning in the readme?

**Comment by slackr31337** [comment]
Hi pl4nty,

You make a good point. I will add a note to the README.
