### ISSUE TITLE
Open Ai functions integration

### ISSUE THREAD

**Issue by kcoderhtml** [slackr31337/PorcupinePipeline#23]
This might be beyond the scope of this project but integrating this with open AI functions could make this very powerful. It could also provide a way to interface with home assistant devices.

**Comment by slackr31337** [comment]
Hi [kcoderhtml](https://github.com/kcoderhtml),

What Open AI functions would you recommend?

Robert

**Comment by kcoderhtml** [comment]
I'm not entirely sure but building a modular system to let people create functions that can be executed, and return information could be very powerful. Now that I'm actually taking time to think about this, it doesn't really seem possible due to the current way the home assistant conversation pipeline works. One of the ways that you could execute actions could be by taking the transcribed audio and sending it to the built-in assist pipeline.
